version: 2.1
jobs:
  build:
    docker:
      - image: your-docker-image # Specify the Docker image you need for your project

    steps:
      - checkout
      - run: # Add your build commands here

  deploy:
    docker:
      - image: your-deployment-image # Specify the Docker image for deployment

    steps:
      - checkout
      - run: # Add your deployment commands here

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

