version: 2.1
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 src/white_noise_portfolio.py
      	name: 
      	command:
      	  npm install --save
  deploy:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4" # Specify the Docker image for deployment

    steps:
      - checkout
      - run: python3 src/white_noise_portfolio.py

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
